logo_image: /assets/img/logo.png
favicon_image: /assets/img/logo.png
navbar_icon: /assets/img/navbar-icon.png
navbar_icon_active: /assets/img/navbar_active.gif
date_image: 'http://via.placeholder.com/40x110/'
urgence_image: 'http://via.placeholder.com/40x110/FF0000'
institutional_website: 'https://www.la-spa.fr/'
sidebar_size_number: 400
progress_bar_color: '#ef5713'
police:
  googlefont_url: >-
    https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700&family=Roboto+Condensed:wght@700
sidebar:
  title: Les animaux ne seront pas les victimes collatérales du COVID-19 !
  subtitle: Je soutiens les refuges de la SPA.
  gift_grid:
    once:
      activate: true
      texte: Je fais un don
      gift_url: ' https://soutenir.la-spa.fr/b?cid=220'
      amount1_number: 100
      amount2_number: 250
      amount3_number: 500
    regular:
      activate: false
      texte: Je fais un don chaque mois
      gift_url: 'https://soutenir.la-spa.fr/b?cid=227'
      amount1_number: 15
      amount2_number: 20
      amount3_number: 30
  defiscalisation: >-
    66% du montant de mon don sont déductibles de l’Impôt sur le Revenu, dans la
    limite de 20% du revenu net imposable.
  monthly: Je souhaite plutôt faire un don tous les mois
  newsletter:
    title: Suivez le direct de la SPA
    subtitle: Abonnez-vous à nos notificationspour ne rien manquer de nos actualités
footer:
  rs:
    fb:
      img: /assets/img/fb.png
      alt: Facebook SPA
      link: 'https://www.facebook.com/spaofficiel'
    tw:
      img: /assets/img/tw.png
      alt: Twitter SPA
      link: 'https://twitter.com/SPA_Officiel'
popup:
  cgu:
    titre: Mentions légales
    contenu_html_code_block: |-
      <h1><small>Mentions légales</small></h1>
            <h2><small>Droits de propriété intellectuelle</small></h2>
            <p>Le présent site est la propriété de {{ include.name }}, qui en est l'auteur au sens des articles L. 111.1 et suivants du Code de la propriété intellectuelle. Les photographies, textes, slogans, dessins, images, séquences animées sonores ou non ainsi que toutes œuvres intégrées dans le site sont la propriété de {{ include.name }} ou de tiers ayant autorisé {{ include.name }} à les utiliser. La reproduction, sur un support papier ou informatique, du site est autorisée sous réserve qu'elle soit strictement réservée à un usage personnel, excluant tout usage à des fins publicitaires et/ou commerciales et/ou d'informations, et qu'elle soit conforme aux dispositions de l'article L122-5 du Code de la Propriété Intellectuelle. A l'exception des dispositions ci-dessus, toute reproduction, représentation, utilisation ou modification, par quelque procédé que ce soit et sur quelque support que ce soit, de tout ou partie du site, de tout ou partie des contenus qui le composent, sans avoir obtenu l'autorisation préalable de {{ include.name }}, est strictement interdite et constitue un délit de contrefaçon.</p>

          <h2><small>Utilisation des données personnelles</small></h2>
          <p>Aucune information personnelle n'est collectée à votre insu. Aucune information personnelle n'est cédée à des tiers. Vous pouvez consulter ce site sans révéler votre identité ou donner la moindre information vous concernant. Les informations que vous nous communiquerez seront traitées selon les dispositions légales applicables et notamment de la Loi "Informatique et Libertés" n°78-17 du 6 janvier 1978. <a href="#" data-open="politiques">Notre politique de protection des données personnelles</a> vous renseigne en détail sur les finalités de notre collecte des données et des fondements juridiques sur lesquels celle-si s'appuie.</p>

          <h2><small>Cookies</small></h2>
          <p>Lors de votre visite sur notre site, nous sommes susceptibles d'implanter un cookie dans votre ordinateur. Un cookie est un petit bloc de données envoyé à votre navigateur par un serveur web et stocké sur le disque dur de votre ordinateur. Le cookie ne nous permet pas de vous identifier personnellement. De manière générale, il nous permet d'enregistrer des informations relatives à la navigation de votre ordinateur sur notre site (les pages que vous avez consultées, la date et l'heure de la consultation, etc.) que nous pourrons lire lors de vos visites ultérieures. Vous pouvez naturellement vous opposer à l'enregistrement de cookies en configurant votre navigateur à partir des "Options" ou "Préférences" de celui-ci. Vous pouvez également supprimer les cookies à tout moment et individuellement en vous rapportant au manuel d'utilisation de votre ordinateur.</p>

          <h2><small>Liens hypertextes</small></h2>
          <p>La mise en place d'un lien hypertexte vers notre site nécessite une autorisation préalable écrite. Faites votre demande à : {{ include.email }}. {{ include.name }} ne peut en aucun cas être tenu pour responsables de la mise à disposition des sites qui font l'objet d'un lien hypertexte à partir du site {{ include.url }} et ne peut supporter aucune responsabilité sur le contenu disponible sur ces sites ou à partir de ces sites.</p>
       
          <h2><small>Editeur</small></h2>
          <p>Ce site est édité par adfinitas, avec l'accord de {{ include.name }} et pour le compte de {{ include.name }}.</p>
          
          <h2><small>Directeur de la publication</small></h2>
          <p>{{ include.directeur }},
              <br/>
              {{ include.name }}.
          </p>
          
          <h2><small>Hébergement du site</small></h2>
          <p>adfinitas
          <br/>Société par actions Simplifiée au capital de 50 000€
          
          <br/><br/><b>Siège social</b>
          <br/>Parc d’Activités « Business Park »
          <br/>Bâtiment A
          <br/>87 rue du Molinel
          <br/>59700 MARCQ EN BAROEUL
          <br/><b>Téléphone :</b> +33.(0)3.28.33.29.60 / Fax : +33.(0)3.28.04.52.41
          <br/><b>SIRET :</b> 432 326 601 00056
          
          <br/><br/><b>Etablissement secondaire</b>
          <br/>132 rue la Fayette
          <br/>75010 Paris
          <br/><b>Téléphone :</b> +33.(0)1.55.33.53.33 / Fax : +33.(0)1.55.33.53.38
          <br/><b>SIRET :</b> 432 326 601 00064
          <br/>Adresse e-mail : adfinitas@adfinitas.fr
          </p>
          
          <h2><small>Réalisation du site</small></h2>
          <p>adfinitas</p>
  privacy:
    titre: Données personnelles
    contenu_html_code_block: ...
faq:
  background: /assets/img/bg-faq.png
appel:
  background: /assets/img/bg-appel.png
  heading:
    title: LES ANIMAUX SERONT-ILS LES VICTIMES COLLATERALES DU COVID-19 ?
    subtitle: 'NON, SI TOUS ENSEMBLE NOUS NOUS MOBILISONS !'
    name: Jacques-Charles Fombonne
    jobtitle: Président bénévole de la SPA
  letter:
    name: Jacques-Charles Fombonne
    jobtitle: Président bénévole de la SPA